Database/week2/fuozbek
FurkannOzbek/hyf-homework pull request #10
Opened 2024-07-12 12:57 UTC by FurkannOzbek

* Part -1 : Change and delete 
* Part -2 : School database
* Part -3 : More Queries
* Part -4 : Creating own dB

2024-07-13 18:45 UTC, NatsGt requested changes
Very good job. The queries are correct, but I do have some comments. The ER diagram also seems good.

2024-07-13 18:45 UTC, NatsGt commented on databases/week2/homework2-part3.sql
> +SELECT * FROM task
The queries are correct, but I think you need to use other tables and values according to the description of the homework

2024-07-13 18:45 UTC, NatsGt commented on databases/week2/homework2-part1.sql
> +
The queries are correct, but you seem to be missing two exercises here.

2024-07-16 12:15 UTC, FurkannOzbek commented on databases/week2/homework2-part1.sql
> +
oh yes my bad got it fixed :)

2024-07-16 12:17 UTC, merged